name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        rm -rf docs
        mkdir docs
        cp -r build/* docs/
        git add docs
        git commit -m "Update GitHub Pages"
        git push
